title:            W.D.Gizzi
tagline:          An extension of my mind.
description:
# An awesome quote for your website
quote:  "The saddest thing in life is wasted talent"
canonical: espresso-math.github.io
#Comment out the below line when pushing to gh-pages
#url: http://10.42.0.1/_site
#For local development only. Comment it out.
#file_end: .html
#url: http://localhost:4000

# Owner/author information
owner:
  name:           William D. Gizzi
  avatar:         avatar.png
  bio:
  email:          gizzidan01@gmail.com
  twitter:        dangizzi
  github:         gizzidan
  instagram:      dangizzi
  dribbble:
  googleplus:
  disqus:
  location:
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "node_modules", "gulpfile.js"]
